"""Make short_code column unique

Revision ID: 5c354a21d37c
Revises: 7ba415a6df63
Create Date: 2024-09-01 11:49:37.405328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c354a21d37c'
down_revision: Union[str, None] = '7ba415a6df63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_urls_short_code', table_name='urls')
    op.create_index(op.f('ix_urls_short_code'), 'urls', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_short_code'), table_name='urls')
    op.create_index('ix_urls_short_code', 'urls', ['short_code'], unique=False)
    # ### end Alembic commands ###
