"""Add access_count column to urls table

Revision ID: 7ba415a6df63
Revises: 
Create Date: 2024-09-01 11:36:23.145506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba415a6df63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('access_count', sa.Integer(), nullable=False))
    op.add_column('urls', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('urls', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_urls_access_count'), 'urls', ['access_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_access_count'), table_name='urls')
    op.drop_column('urls', 'updated_at')
    op.drop_column('urls', 'created_at')
    op.drop_column('urls', 'access_count')
    # ### end Alembic commands ###
