/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QsRgsw1F4iQ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Home() {
  return (
    <section className="flex items-start justify-center w-full py-12 md:py-24 lg:py-32 bg-background">
      <div className="container grid max-w-6xl gap-12 px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-6 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl font-['Bangla', 'sans-serif'] text-foreground">
            Shorten Your Links
          </h2>
          <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Easily shorten your long URLs with our user-friendly tool.
          </p>
        </div>
        <div className="flex flex-col items-center justify-center space-y-6">
          <div className="w-full max-w-md">
            <form className="flex gap-2">
              <Input
                type="text"
                placeholder="Paste your long URL here"
                className="flex-1 rounded-md border border-input bg-background px-4 py-2 text-foreground shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              />
              <Button
                type="submit"
                className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              >
                Shorten
              </Button>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
}
